TrainReader:
  reader_function: ppocr.data.rec.dataset_traversal,LMDBReader
  num_workers: 8
  #lmdb_sets_dir: ./train_data/srn_train_data_duiqi/
  lmdb_sets_dir: ./train_data/data_lmdb_release/validation/
  
EvalReader:
  reader_function: ppocr.data.rec.dataset_traversal,LMDBReader
  lmdb_sets_dir: ./train_data/data_lmdb_release/evaluation/

TestReader:
  reader_function: ppocr.data.rec.dataset_traversal,LMDBReader
  lmdb_sets_dir: ./train_data/data_lmdb_release/evaluation/
  infer_img: ./infer_img
